name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: get current version number
      run: |
           mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -Doutput=.currentVersion
           mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -Dartifact=com.github.siom79.japicmp:japicmp:0.14.3 -DoutputDirectory=.
    - name: create version number
      run: |
           echo $(echo $GITHUB_SHA | cut -c1-7) > .version           
    - name: Build
      run: mvn clean install
    - name: Set version
      run: mvn versions:set -DnewVersion="$(cat .version)"
    - name: Deploy
      run: mvn --settings settings.xml deploy -X -DskipTests=true
      env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
